### PR TITLE
Add support for extracting the DDR firmware binaries from v3 images

### PR DESCRIPTION
**Pull request by xdarklight**
This is useful for retrieving the DDR firmware binaries for G12A boards.

@superna9999 do you have any idea what that 0x20 byte header is in front of the actual `fip_ddrfw_toc_entry`?

### CODE REVIEW

**Comment by repk** [comment]
Sounds good to me. I'll just take a look if I can grasp what this 0x20 byte header is before merging that.

**Comment by repk** [comment]
Hi @xdarklight,

I have finally took time to look at it, so first of all thanks a lot for your PR and sorry for long delay.

For what I could guess, the 0x20 byte header in front of the actual `fip_ddrfw_toc_entry` could be the SHA-256 hash of the whole file.

Do you think this could make sense here ?

**Comment by xdarklight** [comment]
> I have finally took time to look at it, so first of all thanks a lot for your PR and sorry for long delay.

Thanks - and don't worry about a few days of delay!

> For what I could guess, the 0x20 byte header in front of the actual `fip_ddrfw_toc_entry` could be the SHA-256 hash of the whole file.
> 
> Do you think this could make sense here ?

Oh, this is actually more simple than I anticipated. I updated the code in this pull request accordingly.

**Comment by repk** [comment]
Looks good to me.
Thanks for the PR.

**Pull request merged**
